### ISSUE TITLE
 Property Field types issues with "language", "country", "choice" and "locale"

### ISSUE THREAD

**Issue by ThiloWitt** [zikula-modules/Profile#107]
Property Field types "language" and "country" do not show the "language" and "country" names in Profile/display but their codes. E.g.: Language = de; Country = DE. There is a similar issue with the "choice" field type, which shows "key" instead of "value" provided in the property definition.

Property Field type "locale" displays an empty drop down list when creating a new user or updating an existing one, so no value can be chosen.

PHP 7.2.18
Zikula 2.0.13
Profile 3.0.5

**Comment by Guite** [comment]
This problem is already fixed in the latest versions (that are for core 3 though which is not ready nor released yet).

Here is the patch for the core 2 version as a reference (also for other users):

Change https://github.com/zikula-modules/Profile/blob/3.0.5/Form/Type/ChoiceFormOptionsArrayType.php#L63 to: `$newArray[trim($k)] = trim($v);`
