### ISSUE TITLE
Translations not working in Zikula 1.4.0

### ISSUE THREAD

**Issue by nmpetkov** [zikula-modules/Profile#55]
Profile and Legal modules are included in Zikula 1.4.0 distribution. For both modules translations are not working.
How to reproduce:
1. Install Profile module.
2. Prepare translation from `modules/zikula/profile-module/Resources/locale/module_profile.pot`. There is one already there for English, just prepare for other language.
3. Translate all or some of strings ("User Information", "_UREALNAME")..
4. Go to "New account registration" page in the frontend. Translations not working both for English and other language:
![image](https://cloud.githubusercontent.com/assets/628801/9713513/8610f9ce-555a-11e5-8b8f-47e9ce49345e.png)
5. In admin area translations also not working.

I guess it is core issue, because of special place for Profile and legal modules.

**Comment by craigh** [comment]
This is **not** a core issue as it deals with the translation of so-called "DUD" (Dynamic User Data). Which is entirely controller by Profile. This has been left undone because for Core-2.0 we will use a Doctrine inherent feature to accomplish same. The old method you see here is actually legacy from PostNuke (pre-zikula) days and is basically translation by constant strings.

**Comment by craigh** [comment]
fixed in master
