### ISSUE TITLE
Upgrade Profile from ZK 1.3 to ZK 1.5

### ISSUE THREAD

**Issue by KratorD** [zikula-modules/Profile#91]
I have upgrade my ZK from 1.3.10 to 1.5.1. When the process ends, i access to extension module and i can see two profile modules instances (one in my language (perfil version 1.6.2 and active), and other in english (profile version 3.0.2 in status not installed).

I cant init the upgrade process from 1.6.2 to 3.0.2

Futhermore, in the file ProfileModuleInstaller.phpm; function upgrade, i can see
`// Only support upgrade from version 1.6 and up. Notify users if they have a version below that one.
        if (version_compare($oldVersion, '2.0', '<')) {
            // Inform user about error, and how he can upgrade to this version
            $this->addFlash('error', $this->__('Notice: This version does not support upgrades from versions less than 2.0. Please upgrade before upgrading again to this version.'));

            return false;
        }`

Profile for ZK 1.3.x have the version 1.6.2, Profile for ZK 1.4.x is 2.0, and Profile for ZK 1.5 or 2.0 is 3.0.
So, if i upgrade my ZK from 1.3.x to 1.5.x, how must i proceed? I can't understand this

Thanks.

**Comment by Kaik** [comment]
Hi, I remember this issue as it is most probably caused because of https://github.com/zikula-modules/Profile/blob/3.0.2/composer.json#L25 which is different than your old name.
Ways to fix it change name in db (old module row ) or add your module name in above line ```["Profile", "perfil"]```
You might need to remove new profile module row created in modules table (not the old one!!!)
clear cache and then see what extensions list is showing.

**Comment by Kaik** [comment]
Hi, I have 1.6.2 as well. I have checked what happens between 2.0 and 1.6.2 during the upgrade and basically, nothing happens so I think it is safe to change the version to 2.0.0 in your tables so 3x upgrade will work.

There are few other issues which might end up in a failed upgrade.
1. user_property table make sure it is filled with data I have missing validation fields and other bits - very old DB since PostNuke and I have played with those properties before. One bad row and upgrade fails data in the table is lost you need to start again with fresh tables.

2. users_attributes if you have lots of data here then you need to increase php execution time I have 300k and it fails because of it.. apart from that it would be good to investigate data you have there and fix missing corrupted/data.

I have just tried few times I have not upgraded it yet so there might be more things to do before upgrade. I will do it soon need to finish work on Dikzus first.

**Comment by Guite** [comment]
@Kaik how to proceed with this? Anything to be done specifically inside the Profile module?

**Comment by Kaik** [comment]
Hmm... there is not much you can do apart from writing **proper docs**.
Main issue is about different old profile module name in db than expected by new module, it was a common problem with other modules as well. I think you cannot predict those names as it was editable (I had Polish word there). So after upgrade new profile module status is "Not installed". Before upgrade right after uploading new files, profile module name should be changed manually in database to Profile then it will work.

Issues added by my well... one could imagine to have that user property table to be checked before deleting all stuff, and then fail... I think I have finished it with raw sqls due to performance issues...

I think it would be better to have some sort of an upgrade via import feature but obviously there is no manpower... so information about those errors in docs including this ticked will be the best thing we can do... I do not think there is many people left with 1.3 sites anymore...

**Comment by Guite** [comment]
Closing.
